version: "3"
services:
  app:
    build: .   
    command: npm start
    volumes:
      - .:/app/
      - /app/node_modules
    ports:
      - "3000:3000"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.alertas.entrypoints=websecure"
      - "traefik.http.routers.alertas.rule=Host(`alertas.miperu.org`)"

networks:
  proxy:
    external: true